esphome:
  name: keyboard
  friendly_name: keyboard

esp32:
  board: esp32dev
  framework:
    type: arduino



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HA-ENCRYPTION-KEY"

ota:
  - platform: esphome
    password: "ESPHOME-OTA-PWD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keyboard Fallback Hotspot"
    password: "XiNWRHAhlh0A"

captive_portal:
    
matrix_keypad:
  id: mykeypad
  rows:
    - pin: GPIO18
    - pin: GPIO19
    - pin: GPIO21
  columns:
    - pin: GPIO32
    - pin: GPIO33
    - pin: GPIO25
    - pin: GPIO26
    - pin: GPIO27
    - pin: GPIO14
  keys: "qwertyuiopasdfghjk"
    
output:
  - platform: ledc
    id: L0x0ledR
    pin: GPIO4
  - platform: ledc
    id: L1x0ledR
    pin: GPIO2
  - platform: ledc
    id: L0x5ledY
    pin: GPIO16
  - platform: ledc
    id: L1x5ledG
    pin: GPIO17

light:
  - platform: monochromatic
    output: L0x0ledR
    name: red led 0x0 
  - platform: monochromatic
    output: L1x0ledR
    name: red led 1x0
  - platform: monochromatic
    output: L0x5ledY
    name: yellow led 0x5 
  - platform: monochromatic
    output: L1x5ledG
    name: green led 1x5

binary_sensor:
# ROW 0
  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x0"
    row: 0
    col: 0
    name: "+"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x1L"
    row: 0
    col: 1
    name: "FMB scene"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x2"
    row: 0
    col: 2
    name: "Panel I/O"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x3"
    row: 0
    col: 3
    name: "Vent FULL"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x4"
    row: 0
    col: 4
    name: "Main Lights"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K0x5"
    row: 0
    col: 5
    name: "Monitor OFF"


# ROW 1
  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x0"
    row: 1
    col: 0
    name: "-"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x1L"
    row: 1
    col: 1
    name: "Unnamed scene"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x2"
    row: 1
    col: 2
    name: "Light behind speaker"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x3"
    row: 1
    col: 3
    name: "Vent CLSD"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x4"
    row: 1
    col: 4
    name: "Above desk Lights"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K1x5"
    row: 1
    col: 5
    name: "Pause/Play"

# ROW 2
  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x0"
    row: 2
    col: 0
    name: "Exit"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x1L"
    row: 2
    col: 1
    name: "7"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x2"
    row: 2
    col: 2
    name: "Hallway lights"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x3"
    row: 2
    col: 3
    name: "FAN"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x4"
    row: 2
    col: 4
    name: "Under door lights"

  - platform: matrix_keypad
    keypad_id: mykeypad
    id: "K2x5"
    row: 2
    col: 5
    name: "Open gate"

sensor:
  - platform: adc
    pin: GPIO34
    name: "Battery voltage"
    update_interval: 1min
